#!/usr/bin/env python3
"""Copy the built-in palettes out of BuiltInThemes.swift and into the website.

The landing page lets you try every theme the app ships with, which only works
if it knows what they are. Rather than keeping a second copy by hand — which
would be wrong the first time a colour changed and nobody would notice, because
a slightly-off website looks exactly like a correct one — the palettes are read
straight from the Swift source and written into the marked block in
Tools/pages_index.html.

    Tools/sync_themes.py            # rewrite the block
    Tools/sync_themes.py --check    # fail if it's out of date (CI)

The System theme is skipped on purpose: it has no palette, because it paints
with macOS's own semantic colours, and there is nothing to show in a swatch.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "betterTextEdit/Services/BuiltInThemes.swift"
PAGE = ROOT / "Tools/pages_index.html"

BEGIN = "/* THEMES:BEGIN — generated by Tools/sync_themes.py, do not edit */"
END = "/* THEMES:END */"

# Only the tokens the page actually paints with. Reading the rest would put
# a dozen unused colours into every visitor's download.
WANTED = [
    "background", "foreground", "currentLine", "separator", "accent",
    "comment", "selection", "caret", "keyword", "string", "number",
    "type", "function", "variable", "operator", "punctuation",
]


def read_themes() -> list[dict]:
    src = SOURCE.read_text(encoding="utf-8")

    # The declaration order in the `dark` and `light` arrays is the order the
    # app lists them in, so the site matches what's in Settings.
    listed: list[str] = []
    for group in ("dark", "light"):
        match = re.search(rf"static let {group}: \[EditorTheme\] = \[(.*?)\]", src, re.S)
        if match:
            listed += re.findall(r"\b([a-z][A-Za-z0-9]*)\b", match.group(1))

    found: dict[str, dict] = {}
    for match in re.finditer(
        r'private static let (\w+) = make\(\s*"([^"]+)",\s*"([^"]+)",\s*dark: (true|false),\s*\[(.*?)\]\)',
        src,
        re.S,
    ):
        var, ident, name, dark, body = match.groups()
        colors = dict(re.findall(r'\.(\w+): "(#[0-9a-fA-F]{6})"', body))
        missing = [key for key in WANTED if key not in colors]
        if missing:
            raise SystemExit(f"error: theme '{name}' is missing {', '.join(missing)}")
        found[var] = {
            "id": ident,
            "name": name,
            "dark": dark == "true",
            "colors": {key: colors[key] for key in WANTED},
        }

    themes = [found[var] for var in listed if var in found]
    if not themes:
        raise SystemExit("error: no themes found — has BuiltInThemes.swift been restructured?")

    unlisted = set(found) - set(listed)
    if unlisted:
        print(f"note: defined but not in the dark/light arrays: {', '.join(sorted(unlisted))}",
              file=sys.stderr)

    return themes


def render(themes: list[dict]) -> str:
    lines = [BEGIN, "const THEMES = ["]
    for theme in themes:
        lines.append("  " + json.dumps(theme, separators=(",", ":"), ensure_ascii=False) + ",")
    lines += ["];", END]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the page is out of date")
    args = parser.parse_args()

    themes = read_themes()
    page = PAGE.read_text(encoding="utf-8")

    pattern = re.compile(re.escape(BEGIN) + ".*?" + re.escape(END), re.S)
    if not pattern.search(page):
        raise SystemExit(f"error: no THEMES block in {PAGE.name}")

    # A plain replace would treat backslashes in the JSON as group references.
    updated = pattern.sub(lambda _: render(themes), page)

    if args.check:
        if updated != page:
            print("error: Tools/pages_index.html is out of date with BuiltInThemes.swift.\n"
                  "       Run: Tools/sync_themes.py", file=sys.stderr)
            return 1
        print(f"themes in sync ({len(themes)})")
        return 0

    if updated == page:
        print(f"themes already up to date ({len(themes)})")
    else:
        PAGE.write_text(updated, encoding="utf-8")
        print(f"wrote {len(themes)} themes into {PAGE.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
